### ISSUE TITLE
Why use the example HandroidLoggerAdapter changes if it makes no difference?

### ISSUE THREAD

**Issue by krokofant** [mvysny/slf4j-handroid#3]
```java
HandroidLoggerAdapter.DEBUG = BuildConfig.DEBUG;
HandroidLoggerAdapter.ANDROID_API_LEVEL = Build.VERSION.SDK_INT;
HandroidLoggerAdapter.APP_NAME = "MyApp";
```

If the 23 character limit still exists on devices then why encourage setting the ANDROID_API_LEVEL at a high sdk value?

From the docs
> Set this to 24 or higher, to notify Handroid that Android finally dropped the retarded 23 character limit on logger name.

**Comment by mvysny** [comment]
Yeah, sorry about that. I was happy to learn that Android dropped the 23 char limit, only to learn in #2 that it doesn't work. I will thus probably remove the Android_api_level setting since it's broken on some androids. Currently just set it to 1.

**Comment by krokofant** [comment]
I understand your frustration 😅 Thanks for the fixes!

**Comment by mvysny** [comment]
The `HandroidLoggerAdapter.ANDROID_API_LEVEL` is ignored, thus slf4j-Handroid will always use the 'MyApp:MainActivity' format. Don't forget to fill in the `HandroidLoggerAdapter.APP_NAME` setting ;)
