### ISSUE TITLE
Missing proguard rules for Crashlytics methods cause NoSuchMethodException

### ISSUE THREAD

**Issue by simonlaalo** [mvysny/slf4j-handroid#4]
When the slf4j-handroid is loaded and it attempts to get the Crashlytics.log and Crashlytics.logException methods, it won't find them if they are not called directly within the application code and throw a NoSuchMethodException. These methods will have been removed during the build process and thus unavailable at runtime. 
Because of where these methods are loaded by slf4j-handroid, this happens whether the caller wants Crashlytics integration or not.

Adding rules to the proguard-rules (proguard-rules.pro), keeping the Crashlytics static methods, fixes this problem.

```
-keep class com.crashlytics.android.Crashlytics {
    public static void log(int, java.lang.String, java.lang.String);
    public static void logException(java.lang.Throwable);
}
```

Thanks so much for putting this library together

**Comment by mvysny** [comment]
Hey, thanks for letting me know! I'm not using proguard myself so I do not know where the file should go. I'm guessing the root of the jar file, but can you guide me a bit there please?

**Comment by mvysny** [comment]
Moved to https://gitlab.com/mvysny/slf4j-handroid
